---

version: '3.7'
services:
  tf:
    build:
      context: .
      dockerfile: dockerfiles/gpu.python.Dockerfile
      args:
        CUDA: 10.1
    image: softwrdev/tensorflow:latest-gpu-python-py37
